P = {
1: ("A", "Moist, unstable air rises readily, producing cumuliform clouds, turbulence and showery precipitation, usually with good visibility outside the showers.", [("phak","12","unstable air")]),
2: ("A", "Part 107 prohibits operating in Class B, C or D airspace, or in the surface area of Class E designated for an airport, without prior authorization from ATC.", [("cfr","107.41")]),
3: ("C", "Operations in Class C airspace require prior ATC authorization. A visual observer and a flight plan are not required.", [("cfr","107.41")]),
4: ("B", "High density altitude means thinner air. The propeller has less air to work with, so it produces less thrust and propeller efficiency decreases.", [("phak","4-4","density altitude")]),
5: ("C", "The circled C next to 122.8 in the Coeur d'Alene data block marks it as the CTAF. 135.075 is the AWOS.", [("aim","4-1-9")]),
6: ("A", "Effective scanning uses a series of short, regularly spaced eye movements, briefly focusing on each segment of the sky.", [("phak","14-28","scan"),("aim","8-1-6")]),
7: ("C", "At 30° of bank in level flight the load factor is 1.154 G, so the structure must support 33 × 1.154 ≈ 38 pounds.", [("phak","5","load factor")]),
8: ("B", "The outer circle of Savannah Class C is labeled 41/13: ceiling 4,100 feet MSL, floor 1,300 feet MSL. Class C altitudes on sectionals are in MSL.", [("aim","3-2-4")]),
9: ("C", "The caution box warns of an unmarked balloon on a cable up to 3,008 feet MSL. Charted altitudes are MSL unless marked otherwise.", []),
11: ("A", "The Chart Supplement U.S. (formerly the Airport/Facility Directory) provides the most comprehensive information on a given airport.", [("phak","14-3","Chart Supplement")]),
12: ("C", "Taking risks to impress others is the macho attitude (\"I can do it\"). Its antidote is \"Taking chances is foolish.\"", [("phak","2-5","Macho"),("rmh","3-2","Macho")]),
13: ("B", "The site is inside the Jamestown Class E surface area (dashed magenta line). Part 107 requires ATC authorization in Class E airspace designated for an airport.", [("cfr","107.41")]),
14: ("C", "NOTAMs are available through a flight service briefing, including online services such as 1800wxbrief.com.", [("aim","5-1-3")]),
15: ("B", "Crew resource management applies to every phase of the operation, from planning and preflight through recovery and debrief.", [("phak","2-4","Crew Resource Management")]),
16: ("C", "\"Fly first, ask questions later\" is the impulsive attitude (\"Do it quickly\"). Its antidote is \"Not so fast. Think first.\"", [("phak","2-5","Impulsivity"),("rmh","3-2","Impulsivity")]),
17: ("C", "A healthy safety culture recognizes hazardous attitudes and situations and sets standard operating procedures that put safety first. Accepting accidents or setting crash quotas does the opposite.", [("phak","2-5","hazardous attitudes"),("phak","2","aeronautical decision-making")]),
18: ("A", "Left traffic for runway 13 puts the downwind leg on the left of the landing direction (130°), which is the northeast side. An aircraft at midfield left downwind is therefore east of the runway.", [("aim","4-3-3")]),
19: ("C", "A remote pilot who deviates from Part 107 in an in-flight emergency must send a written report of the deviation to the FAA, but only upon request.", [("cfr","107.21")]),
20: ("B", "Load factor increases whenever the aircraft is maneuvered out of straight-and-level flight, for example in turns, pull-ups or gusts.", [("phak","5","load factor")]),
21: ("C", "A stall occurs when the wing exceeds its critical angle of attack, regardless of speed or weight.", [("phak","5-3","critical angle of attack")]),
22: ("C", "Accidents are rarely one event; they are a chain of decisions and events. The Risk Management Handbook identifies inadequate risk management as the common thread, so identifying hazards and managing risk is how a pilot breaks the chain before its final link.", [("rmh","3-4","chain of events"),("phak","2-12","chain of events")]),
23: ("B", "Fatigue is an impairment. It degrades attention, concentration, coordination and communication, and often goes unnoticed by the pilot until errors are made.", [("phak","17-13","Fatigue"),("phak","2-8","Fatigue")]),
24: ("C", "Plotting 47°40'N, 101°26'W (20 minutes south of 48° N and 26 minutes west of 101° W) lands on Garrison airport.", [("phak","16","latitude")]),
25: ("A", "SPECI KMDW ... 1 1/2SM RA OVC007 decodes as visibility 1-1/2 statute miles in rain, overcast ceiling at 700 feet.", [("phak","13","METAR")]),
26: ("A", "18004KT means wind from 180° true at 4 knots. METAR wind directions are referenced to true north.", [("phak","13","METAR")]),
27: ("A", "During civil twilight (30 minutes before sunrise or after sunset) the small UA needs lighted anti-collision lighting visible for at least 3 statute miles.", [("cfr","107.29")]),
28: ("A", "Loading and CG limits for a specific aircraft come from that aircraft's Pilot's Operating Handbook or UAS flight manual.", [("phak","10","center of gravity")]),
29: ("A", "The remote pilot in command is directly responsible for the operation and must complete the preflight assessment, including making sure there is enough power and performance for the intended flight.", [("cfr","107.19"),("cfr","107.49")]),
30: ("B", "VR routes with four-digit numbers are military training routes flown at or below 1,500 feet AGL, which includes the altitudes where small UA operate.", [("aim","3-5-2")]),
31: ("B", "Lines of latitude (parallels) measure degrees north and south of the equator. Longitude measures east and west of the Prime Meridian.", [("phak","16","latitude")]),
32: ("A", "If the manufacturer gives no maintenance schedule, the operator should set up a scheduled maintenance protocol. Part 107 still requires the UAS to be in a condition for safe operation.", [("cfr","107.15")]),
33: ("A", "Before each flight the remote pilot in command must check the small UAS to determine whether it is in a condition for safe operation.", [("cfr","107.15")]),
34: ("A", "A small UA must be registered by its owner, unless the owner is under 13. In that case someone at least 13 years old must register it.", [("cfr","48.25")]),
36: ("C", "Even small amounts of alcohol impair judgment and decision-making. Water does not speed the elimination of alcohol from the body.", [("phak","17-15","alcohol")]),
37: ("C", "The remote PIC must make sure everyone directly participating is briefed on operating conditions, emergency and contingency procedures, roles and hazards.", [("cfr","107.49")]),
38: ("B", "Stable air resists vertical motion. It typically brings stratiform clouds, smooth air, poor visibility and steady precipitation.", [("phak","12","stable air")]),
39: ("A", "Inversions are layers of smooth, stable air that trap moisture and pollutants beneath them. With high relative humidity, expect smooth air with poor visibility in fog, haze or low clouds.", [("phak","12-13","inversion")]),
40: ("C", "The remote PIC may reduce the intensity of the anti-collision lighting, but never turn it off, when operating conditions make that safer.", [("cfr","107.29")]),
41: ("A", "If a standard remote identification aircraft stops broadcasting, the person manipulating the controls must land as soon as practicable.", [("cfr","89.110")]),
42: ("C", "The serial number of a standard remote ID aircraft, or of the broadcast module, must be listed on the aircraft's Certificate of Aircraft Registration.", [("cfr","89.110"),("cfr","89.115")]),
43: ("B", "Full dark adaptation takes about 30 minutes, and a moment of bright light can undo it. Use dim or red light after preflighting under bright light.", [("phak","17","dark adaptation"),("aim","8-1-6")]),
44: ("A", "Category 1 operations over people require a small UA that weighs 0.55 pounds or less, including everything on board, with no exposed rotating parts that would lacerate skin.", [("cfr","107.110")]),
45: ("A", "Category 4 small UA must have an airworthiness certificate issued under part 21.", [("cfr","107.140")]),
46: ("B", "Remote pilots must comply with TFRs (§§ 91.137–91.145 and 99.7). Sponsorship gives no exemption, so you may not fly in the TFR without the specific authorization or waiver the restriction requires.", [("cfr","107.47"),("cfr","91.145")]),
}
FIG = {5:"22",7:"2",8:"23",9:"20",13:"26",14:"20",18:"26",24:"21",25:"12",26:"12",30:"59",31:"26"}
SKIP = {
 10: "Ambiguous: the FAA's guidance (AIM 3-4-5) is to contact flight service or the controlling agency for MOA status; none of the choices clearly matches that.",
 35: "Ambiguous under current 14 CFR 48.15: both A and B describe situations where registration is required.",
}
FIX = {}
