P = {
1: ("B", "For airman certification, the categories of aircraft are airplane, rotorcraft, glider and lighter-than-air (plus powered-lift, powered parachute and weight-shift-control). Gyroplane and helicopter are classes of rotorcraft, and single-/multiengine land/sea are classes of airplane.", [("cfr","61.5"),("cfr","1.1")]),
2: ("B", "An aircraft in distress has the right-of-way over all other air traffic.", [("cfr","91.113")]),
3: ("B", "Operating a product that does not meet an applicable AD is a violation, unless the AD itself allows the operation, for example through a compliance time or a special flight permit to reach a repair facility.", [("cfr","39.7"),("cfr","39.23")]),
4: ("B", "No one may fly in formation except by arrangement with the pilot in command of each aircraft, and formation flight is never allowed while carrying passengers for hire.", [("cfr","91.111")]),
5: ("C", "A standard airworthiness certificate stays in effect as long as maintenance, preventive maintenance and alterations are performed in accordance with parts 43 and 91 and the aircraft is registered in the United States.", [("cfr","21.181")]),
6: ("C", "Low-level wind shear is commonly associated with temperature inversions when the winds just above the inversion are strong. The usual rule of thumb is 25 knots or more at 2,000 to 4,000 feet.", [("phak","12-11","wind shear")]),
7: ("C", "The KMEM TAF valid period 1218/1324 runs from 1800Z on the 12th to 2400Z on the 13th, a 30-hour forecast.", [("phak","13","TAF")]),
8: ("A", "STL at 9,000 feet reads 2332+02: wind from 230° true at 32 knots, temperature +2 °C. Forecast winds aloft are referenced to true north.", [("phak","13","winds and temperatures aloft")]),
9: ("A", "18004KT in the KJFK report means wind from 180° at 4 knots. Wind direction in METARs is referenced to true north.", [("phak","13","METAR")]),
10: ("A", "Ground effect is the interference of the surface with the airflow around a wing within about one wingspan of the ground. It reduces upwash, downwash and wingtip vortices, and with them induced drag.", [("phak","5-11","ground effect")]),
11: ("B", "Climbing out of ground effect, the wing needs a higher angle of attack for the same lift, and induced drag increases. Performance drops, and an airplane lifted off too slowly may settle back.", [("phak","5-11","ground effect")]),
12: ("B", "The antidote for invulnerability (\"It won't happen to me\") is \"It could happen to me.\"", [("phak","2-5","Invulnerability"),("rmh","3-2","Invulnerability")]),
13: ("A", "In straight-and-level, unaccelerated flight the forces are in equilibrium: lift equals weight and thrust equals drag.", [("phak","5-1","four forces")]),
14: ("C", "Every flight is built from four fundamentals: straight-and-level flight, turns, climbs and descents.", [("afh","3")]),
15: ("B", "The 10° left wind correction means the wind is from the left, and groundspeed is 10 knots below TAS, so there is a headwind component. Solving the wind triangle (75 kt at 040° through the air, 65 kt at 050° over the ground) gives wind from about 355° at about 16 knots.", [("phak","16","wind correction angle")]),
16: ("A", "Mercer County to Minot measures about 59 NM on a true course of about 010°. With wind from 330° at 25 knots and 100 knots TAS, the wind correction angle is about 9° left and groundspeed about 80 knots: roughly 44.5 minutes en route plus 3.5 minutes for departure, about 48 minutes.", [("phak","16","groundspeed")]),
17: ("A", "Lakeview (30F) lies in the Class B sector labeled 110/30: ceiling 11,000 feet MSL, floor 3,000 feet MSL.", [("phak","15","class B")]),
18: ("B", "Daytime scanning should use short, regularly spaced eye movements that bring successive 10° sectors into central vision, viewing each for at least 1 second. Peripheral, off-center viewing is a night technique.", [("phak","14-28","scan"),("aim","8-1-6")]),
19: ("A", "14 CFR 1.1 defines an ATC clearance as an authorization by ATC to proceed under specified traffic conditions within controlled airspace, to prevent collisions between known aircraft.", [("cfr","1.1")]),
20: ("A", "Squawk 7700 in a distress or urgency condition to alert ATC radar facilities.", [("aim","6-2-2"),("aim","4-1-20")]),
21: ("B", "At airports without a tower or UNICOM, self-announce on MULTICOM (122.9) about 10 miles out, then on downwind, base, final and when leaving the runway.", [("aim","4-1-9")]),
22: ("A", "Clock positions are relative to the nose. On a heading of 270°, 3 o'clock is 90° to the right, which is north.", [("aim","4-1-15")]),
23: ("A", "A wing stalls when it exceeds its critical angle of attack, regardless of airspeed, flight attitude or weight.", [("phak","5-3","critical angle of attack")]),
24: ("A", "Best glide speed gives the greatest gliding distance for the altitude lost, at the best lift-to-drag ratio.", [("phak","5","glide")]),
25: ("C", "The obstacle southeast of Winnsboro is charted at 903 feet MSL (323 AGL). Clearing it by 500 feet requires 903 + 500 = 1,403 feet MSL.", [("phak","16","obstruction")]),
26: ("A", "Measure 19 minutes south of the 48° N line and 36 minutes west of the 101° W meridian to plot the position. It falls on Fischer (Pvt) airport.", [("phak","16","latitude")]),
27: ("C", "High temperature, high humidity and high density altitude all mean less dense air. The engine makes less power, the propeller produces less thrust and the wing needs more true airspeed, so takeoff and climb performance suffer.", [("phak","4-4","density altitude")]),
28: ("C", "Warmer-than-standard air is less dense, so density altitude is higher than pressure altitude.", [("phak","4-4","density altitude")]),
29: ("A", "Pressure altitude is field elevation plus the conversion factor for the altimeter setting. 29.97 lies between 29.92 (0) and 30.0 (-73), giving about -45 feet, so 1,386 - 45 ≈ 1,341 feet.", [("phak","8","pressure altitude")]),
30: ("C", "The red radial line marks VNE, the never-exceed speed.", [("phak","8","never-exceed speed")]),
31: ("B", "Indicated altitude equals true altitude only under standard atmospheric conditions with the altimeter correctly set, for example at sea level on a standard day. Nonstandard temperature or pressure makes them differ.", [("phak","8-4","true altitude")]),
32: ("B", "An early decision to go around from a poor approach is generally preferable to last-minute attempts to salvage the landing.", [("afh","9")]),
33: ("A", "Currituck County is non-towered (CTAF 122.9). Self-announce your intentions before taxiing and announce the departure runway.", [("aim","4-1-9")]),
34: ("B", "Coeur d'Alene has an AWOS-3 on 135.075, which broadcasts automated weather. 122.8 is the CTAF and 108.8 is the VOR-DME.", [("aim","7-1")]),
35: ("C", "On the V-g diagram the positive limit load factor is the horizontal line along the top of the envelope, from C to E.", [("phak","5","load factor")]),
36: ("C", "MOA stands for military operations area: airspace that separates certain military training activities from IFR traffic.", [("aim","3-4-5")]),
37: ("C", "Gila Bend AF Aux (GXF) has a control tower (CT 127.75) and is surrounded by a dashed blue line, so it is Class D airspace.", [("phak","15","class D")]),
38: ("B", "Sport pilots may not act as pilot in command when flight or surface visibility is less than 3 statute miles, in any airspace.", [("cfr","61.315")]),
39: ("B", "A sport pilot may not fly when the flight or surface visibility is less than 3 statute miles.", [("cfr","61.315")]),
40: ("B", "MULTICOM, used for self-announcing where there is no tower, FSS or UNICOM, is 122.9 MHz.", [("aim","4-1-9")]),
}
FIG = {7:"15",8:"17",9:"12",16:"21",17:"25",25:"24",26:"21",29:"8",33:"20",34:"22",35:"72",36:"26",37:"75",38:"26"}
SKIP = {}
FIX = {37: {"A":"B.","B":"C.","C":"D."}}
