# Original questions written from the text of 14 CFR Part 103 (eCFR). Choices/answers are ours.
Q = [
("What is the maximum empty weight of a powered ultralight vehicle under Part 103?",
 {"A":"Less than 254 pounds, excluding floats and emergency safety devices such as a ballistic parachute.","B":"Less than 254 pounds, including fuel and the pilot.","C":"Less than 155 pounds, excluding floats."},
 "A", "A powered ultralight must weigh less than 254 pounds empty. Floats and safety devices intended for deployment in a potentially catastrophic situation are not counted. The 155-pound limit applies to unpowered ultralights.", [("cfr","103.1")], "weight"),
("What is the maximum fuel capacity of a powered ultralight vehicle?",
 {"A":"5 U.S. gallons.","B":"10 U.S. gallons.","C":"There is no fuel limit; only empty weight is limited."},
 "A", "A powered ultralight may have a fuel capacity of no more than 5 U.S. gallons.", [("cfr","103.1")], "fuel"),
("What is the maximum speed of a powered ultralight in level flight at full power?",
 {"A":"55 knots calibrated airspeed.","B":"63 miles per hour indicated airspeed.","C":"87 knots calibrated airspeed."},
 "A", "A powered ultralight must not be capable of more than 55 knots calibrated airspeed at full power in level flight. 87 knots is a light-sport aircraft figure, not a Part 103 limit.", [("cfr","103.1")], "max speed"),
("What is the maximum power-off stall speed of a powered ultralight?",
 {"A":"24 knots calibrated airspeed.","B":"35 knots calibrated airspeed.","C":"45 knots calibrated airspeed."},
 "A", "The power-off stall speed of a Part 103 powered ultralight may not exceed 24 knots calibrated airspeed.", [("cfr","103.1")], "stall speed"),
("How many occupants may an ultralight vehicle carry?",
 {"A":"One: the operator.","B":"Two, if both are wearing parachutes.","C":"Two, if the second occupant is a flight instructor."},
 "A", "By definition an ultralight is used or intended to be used for manned operation by a single occupant, for recreation or sport purposes only.", [("cfr","103.1")], "single occupant"),
("Which certificates does Part 103 require of an ultralight operator?",
 {"A":"No airman or medical certificate.","B":"A student pilot certificate and a third-class medical.","C":"A sport pilot certificate with an ultralight endorsement."},
 "A", "Ultralight operators are not required to meet any aeronautical knowledge, age or experience requirements, or to hold airman or medical certificates. Training is still strongly recommended.", [("cfr","103.7")], "airman certificate"),
("Must an ultralight vehicle be registered and carry an N-number?",
 {"A":"No. Ultralights are not required to be registered or to bear markings of any type.","B":"Yes, all aircraft operated in the United States must be registered.","C":"Only if it is flown in controlled airspace."},
 "A", "Ultralight vehicles are not required to be registered or to bear markings of any type, and they do not need airworthiness certificates.", [("cfr","103.7")], "registration"),
("Without additional equipment, during what hours may an ultralight be operated?",
 {"A":"Between sunrise and sunset.","B":"From 30 minutes before sunrise to 30 minutes after sunset.","C":"Any time, if the operator remains clear of clouds."},
 "A", "Ultralights may operate only between sunrise and sunset. The twilight periods are allowed only with additional equipment and only in uncontrolled airspace.", [("cfr","103.11")], "sunrise and sunset"),
("An ultralight may fly during the 30-minute twilight periods before sunrise and after sunset only if",
 {"A":"it has an operating anticollision light visible for at least 3 statute miles and stays in uncontrolled airspace.","B":"it has navigation lights and the operator has notified the nearest tower.","C":"the operator holds a private pilot certificate."},
 "A", "Twilight operations (30 minutes before official sunrise and 30 minutes after official sunset) require an operating anticollision light visible for at least 3 statute miles, and all operations must be in uncontrolled airspace.", [("cfr","103.11")], "anticollision light"),
("Who has the right-of-way when an ultralight meets another aircraft?",
 {"A":"The ultralight yields to all aircraft; a powered ultralight also yields to an unpowered ultralight.","B":"The ultralight, because it is the least maneuverable.","C":"Whichever is on the right."},
 "A", "Ultralight operators must see and avoid and yield the right-of-way to all aircraft. Powered ultralights must yield to unpowered ultralights.", [("cfr","103.13")], "right-of-way"),
("Over which areas is ultralight operation prohibited?",
 {"A":"Any congested area of a city, town or settlement, or any open-air assembly of persons.","B":"Only areas with more than 1,000 residents.","C":"Over a congested area below 1,000 feet AGL only."},
 "A", "Part 103 has no altitude exception: no person may operate an ultralight over any congested area of a city, town or settlement, or over any open-air assembly of persons.", [("cfr","103.15")], "congested area"),
("What is required before operating an ultralight in Class B, C or D airspace, or in the surface area of Class E airspace designated for an airport?",
 {"A":"Prior authorization from the ATC facility having jurisdiction over that airspace.","B":"A transponder and two-way radio only.","C":"Nothing, if the flight remains below 500 feet AGL."},
 "A", "Operations in Class A, B, C or D airspace, or within the lateral boundaries of a Class E surface area designated for an airport, require prior authorization from the ATC facility having jurisdiction.", [("cfr","103.17")], "prior authorization"),
("When may an ultralight operate in a restricted or prohibited area?",
 {"A":"Only with permission from the using or controlling agency.","B":"Whenever the area is shown as inactive on the sectional chart.","C":"Never, under any circumstances."},
 "A", "Ultralights may not operate in prohibited or restricted areas unless the operator has permission from the using or controlling agency.", [("cfr","103.19")], "restricted areas"),
("Part 103 requires an ultralight to be operated",
 {"A":"only by visual reference with the surface.","B":"with a GPS when beyond sight of the departure field.","C":"at or below 500 feet AGL at all times."},
 "A", "No person may operate an ultralight except by visual reference with the surface. There is no instrument flying in an ultralight.", [("cfr","103.21")], "visual reference"),
("What are the minimum flight visibility and cloud clearance for an ultralight in Class G airspace at 1,200 feet or less above the surface?",
 {"A":"1 statute mile and clear of clouds.","B":"3 statute miles and 500 feet below the clouds.","C":"5 statute miles and 1,000 feet above the clouds."},
 "A", "The Part 103 table sets 1 statute mile flight visibility and clear of clouds in Class G airspace at 1,200 feet or less above the surface, regardless of MSL altitude.", [("cfr","103.23")], "Class G"),
("What are the ultralight visibility and cloud clearance minimums in Class E airspace below 10,000 feet MSL?",
 {"A":"3 statute miles; 500 feet below, 1,000 feet above and 2,000 feet horizontally from clouds.","B":"1 statute mile and clear of clouds.","C":"5 statute miles; 1,000 feet below and above, and 1 statute mile horizontally."},
 "A", "Below 10,000 feet MSL in Class E, Part 103 requires 3 statute miles visibility and 500 feet below, 1,000 feet above and 2,000 feet horizontally from clouds.", [("cfr","103.23")], "Class E"),
("May an object be dropped from an ultralight vehicle?",
 {"A":"Only if dropping it does not create a hazard to other persons or property.","B":"Never.","C":"Yes, at any time over unpopulated areas."},
 "A", "No person may allow an object to be dropped from an ultralight if doing so creates a hazard to other persons or property.", [("cfr","103.9")], "dropped"),
]
