<?php
// Deployed at api.openchecklists.net/mail-pdf.php (kw3, cPanel user openchkl).
// Generic PDF-attachment mailer. Server-to-server only (called by the ocl-api
// Worker with the shared secret). Body: {email, subject, filename, text, pdf_base64}.
// Secret REDACTED in-repo; set the deployed copy to match the Worker's OCL_PDF_SECRET.
header('Content-Type: application/json');
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') { http_response_code(204); exit; }
if ($_SERVER['REQUEST_METHOD'] !== 'POST') { http_response_code(405); echo '{"error":"method"}'; exit; }
if (($_SERVER['HTTP_X_OCL_SECRET'] ?? '') !== 'REDACTED-SET-TO-OCL_PDF_SECRET') {
    http_response_code(403); echo '{"error":"forbidden"}'; exit;
}
$d = json_decode(file_get_contents('php://input'), true);
if (!$d) { http_response_code(400); echo '{"error":"bad json"}'; exit; }
$email = filter_var(trim($d['email'] ?? ''), FILTER_VALIDATE_EMAIL);
if (!$email) { http_response_code(422); echo '{"error":"invalid email"}'; exit; }
$subject  = substr(preg_replace('/[\r\n]+/', ' ', $d['subject'] ?? 'Your checklist log'), 0, 160);
$fnameRaw = preg_replace('/[^A-Za-z0-9._-]/', '-', substr($d['filename'] ?? 'checklist-log.pdf', 0, 80));
if (substr($fnameRaw, -4) !== '.pdf') $fnameRaw .= '.pdf';
$text = substr($d['text'] ?? 'Your checklist log PDF is attached.', 0, 4000);
$b64 = $d['pdf_base64'] ?? '';
if (strpos($b64, ',') !== false) $b64 = substr($b64, strpos($b64, ',') + 1);
$pdf = base64_decode($b64, true);
if ($pdf === false || strlen($pdf) < 200) { http_response_code(422); echo '{"error":"invalid pdf"}'; exit; }
if (strlen($pdf) > 4 * 1024 * 1024) { http_response_code(413); echo '{"error":"pdf too large"}'; exit; }
if (substr($pdf, 0, 5) !== '%PDF-') { http_response_code(422); echo '{"error":"not a pdf"}'; exit; }
$boundary = 'ocl' . bin2hex(random_bytes(8));
$body  = "--$boundary\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Transfer-Encoding: 7bit\r\n\r\n";
$body .= $text . "\r\n\r\nGenerated by openchecklists.net. Not approved data - verify against your aircraft's documentation.\r\n";
$body .= "--$boundary\r\nContent-Type: application/pdf; name=\"$fnameRaw\"\r\n";
$body .= "Content-Transfer-Encoding: base64\r\nContent-Disposition: attachment; filename=\"$fnameRaw\"\r\n\r\n";
$body .= chunk_split(base64_encode($pdf)) . "\r\n--$boundary--";
$headers = implode("\r\n", [
    "From: Open Checklists <admin@openchecklists.net>",
    "Reply-To: admin@openchecklists.net", "X-Mailer: openchecklists.net",
    "MIME-Version: 1.0", "Content-Type: multipart/mixed; boundary=\"$boundary\"",
]);
$sent = mail($email, $subject, $body, $headers, '-f admin@openchecklists.net');
if ($sent) { echo json_encode(['ok' => true, 'msg' => "Sent to $email"]); }
else { http_response_code(500); echo json_encode(['error' => 'mail failed']); }
