#!/usr/bin/env python3
"""Write worker/ocl-api/quiz-answers.js from quiz/*.json.

The worker credits quiz points only for a correct answer to a real question, once
per question per pilot, so it needs the answer key. Run before deploying the
worker (deploy.sh does).
"""
import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "worker" / "ocl-api" / "quiz-answers.js"


def main() -> None:
    key = {}
    for f in sorted((REPO / "quiz").glob("*.json")):
        d = json.loads(f.read_text())
        if not isinstance(d, dict) or "questions" not in d:
            continue
        key[d["id"]] = {str(q["n"]): q["answer"] for q in d["questions"]}
    OUT.write_text("// Generated by tools/quiz_answers.py from quiz/*.json — do not edit.\n"
                   f"export const QUIZ_ANSWERS = {json.dumps(key, sort_keys=True)};\n")
    print(f"wrote {OUT.relative_to(REPO)}: {sum(len(v) for v in key.values())} answers")


if __name__ == "__main__":
    main()
